[package]
name = "dog_center_api"
version = "0.1.0"
edition = "2024"

[lib]
name = "dog_center_api"
path = "src/lib.rs"

[dependencies]
async-trait = { version = "0.1" }
axum = "0.8.3"
chrono = { version = "0.4.40", features = ["serde"] }
dotenv = "0.15.0"
listenfd = "1.0.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { version = "0.8.3", features = [
  "runtime-tokio-native-tls",
  "postgres",
  "chrono",
  "uuid",
  "sqlite",
] }
tokio = { version = "1.44.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors"] }
uuid = { version = "1.16.0", features = ["serde", "v4"] }
tracing = "0.1" # Bibliothèque principale pour les logs
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "fmt",
  "time",
] } # Gestionnaire de logs
validator = { version = "0.20.0", features = ["derive"] }
async-graphql = "7.0.16"
async-graphql-axum = "7.0.16"
reqwest = { version = "0.12.15", features = ["json"] }
testcontainers = "0.18.0"
thiserror = "2.0.12"
base64 = "0.22.1"
garde = { version = "0.22.0", features = ["email", "full", "phone-number"] }
