### dog
# get by id
GET http://127.0.0.1:3000/api/dogs/83c928fc-c90f-46b9-a8fa-6752bb735c8f

### create
POST http://127.0.0.1:3000/api/dogs
Content-type: application/json

{
    "name": "pupuce",
    "birthdate": "2025-04-23T08:18:00Z",
    "races": ["bichon"],
    "sex": "F"
}
